apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api-deployment
  namespace: kubernetes-cluster-shweta03
  labels:
    app: dotnet-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
        - name: dotnet-api
          image: shweyasingh/i-shweta03-develop:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
