apiVersion: v1
kind: Service
metadata:
  name: dotnet-api-service-develop
  namespace: kubernetes-cluster-shweta03
spec:
  type: NodePort
  selector:
    app: dotnet-api
  ports:
    - protocol: TCP
      nodePort: 30158
      port: 80
      targetPort: 80
